InteractiveUser/src/MvcClient/Models/ErrorViewModel.cs
namespace MvcClient.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InteractiveUser/src/MvcClient/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MvcClient.Models
{
    public class LoginViewModel
    {
        [Required]
        public string Username { get; set; }
        [Required]
        public string Password { get; set; }
        public bool RememberMe { get; set; }
        public string ReturnUrl { get; set; }
    }
}

InteractiveUser/src/MvcClient/Models/Movie.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MvcClient.Models
{
    public class Movie
    {
        public int Id { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 3)]
        public string Title { get; set; }

        [Display(Name = "Release Date")]
        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }

        [DataType(DataType.Currency)]
        [Range(1, 100)]
        public decimal Price { get; set; }

        [Required]
        [MaxLength(30)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z""'\s-]*$")]
        public string Genre { get; set; }

        [Required]
        [MaxLength(5)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z0-9""'\s-]*$")]
        public string Rating { get; set; }
    }
}

InteractiveUser/src/MvcClient/Models/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MvcClient.Models
{
    public class RegisterViewModel
    {
        [Required]
        public string Username { get; set; }
        [Required]
        public string Password { get; set; }
        [Required]
        [Display(Name = "Confirm Password")]
        public string ConfirmPassword { get; set; }
        public bool RememberMe { get; set; }
    }
}

InteractiveUser/src/MvcClient/Controllers/AccountController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MvcClient.Models;

namespace MvcClient.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Logout()
        {
            return SignOut("Cookies", "oidc");
        }

        public IActionResult Register()
        {
            return View();
        }
    }
}

InteractiveUser/src/MvcClient/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcClient.Models;

namespace MvcClient.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            var error = new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier };
            _logger.LogError($"An error ocurred at RequestId {error.RequestId}");

            return View();
        }
    }
}

InteractiveUser/src/MvcClient/Controllers/MovieController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MvcClient.Models;
using MvcClient.Services;

namespace MvcClient.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieService _service;

        public MovieController(IMovieService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var movies = await _service.GetMovies();

            return View(movies);
        }

        public async Task<IActionResult> Details(int id)
        {
            var movie = await _service.GetMovie(id);

            return View(movie);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Movie movie)
        {
            if (ModelState.IsValid)
            {
                await _service.CreateMovie(movie);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var movie = await _service.GetMovie(id);

            return View(movie);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _service.UpdateMovie(id, movie);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var movie = await _service.GetMovie(id);

            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteMovie(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

InteractiveUser/src/MvcClient/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

InteractiveUser/src/MvcClient/Views/Movie/Create.cshtml
@model Movie

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Movie</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control"/> 
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control"/> 
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control"/> 
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>    
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control"/> 
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>    
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control"/> 
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>    
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to list</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InteractiveUser/src/MvcClient/Views/Movie/Delete.cshtml
@model Movie

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>

<div>
    <h4>Movie</h4>
    <hr/>
    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.Title)</dt>
        <dd>
            @Html.DisplayFor(model => model.Title)</dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)</dt>
        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)</dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genre)</dt>
        <dd>
            @Html.DisplayFor(model => model.Genre)</dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)</dt>
        <dd>
            @Html.DisplayFor(model => model.Price)</dd>
        <dt>
            @Html.DisplayNameFor(model => model.Rating)</dt>
        <dd>
            @Html.DisplayFor(model => model.Rating)</dd>
    </dl>

    <form asp-action="Delete" method="POST">
        <input type="hidden" asp-for="Id"/>
        <input type="submit" value="Delete" class="btn btn-danger"/>
        <a asp-action="Index">Back to list</a>
    </form>
</div>

InteractiveUser/src/MvcClient/Views/Movie/Details.cshtml
@model Movie

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Movie</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Title)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Title)</dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.ReleaseDate)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.ReleaseDate)</dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Genre)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Genre)</dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Price)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Price)</dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Rating)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Rating)</dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to list</a>
</div>

InteractiveUser/src/MvcClient/Views/Movie/Edit.cshtml
@model Movie

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Movie</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control"/> 
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control"/> 
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>    
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control"/> 
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>    
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control"/> 
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>    
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control"/> 
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>    
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
    </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to list</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InteractiveUser/src/MvcClient/Views/Movie/Index.cshtml
@model IEnumerable<Movie>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <th>@Html.DisplayNameFor(model => model.Title)</th>
        <th>@Html.DisplayNameFor(model => model.ReleaseDate)</th>
        <th>@Html.DisplayNameFor(model => model.Genre)</th>
        <th>@Html.DisplayNameFor(model => model.Price)</th>
        <th>@Html.DisplayNameFor(model => model.Rating)</th>
        <th></th>
    </thead>
    <tbody>
    @foreach (var movie in Model)
    {
        <tr>
            <td>@Html.DisplayFor(model => movie.Title)</td>
            <td>@Html.DisplayFor(model => movie.ReleaseDate)</td>
            <td>@Html.DisplayFor(model => movie.Genre)</td>
            <td>@Html.DisplayFor(model => movie.Price)</td>
            <td>@Html.DisplayFor(model => movie.Rating)</td>
            <td>
                <a asp-action="Edit" asp-route-id="@movie.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@movie.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@movie.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

InteractiveUser/src/MvcClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - Moive App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container"> 
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial"/>
                    <ul class="navbar-nav flex-grow-1"> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Index" asp-controller="Home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Index" asp-controller="Movie">Movie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Privacy" asp-controller="Home">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">     
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Movie App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>